package org.example.medicaldiagnosisapi.enums;

public enum DoctorSpecialty {
  CARDIOLOGY,
  DERMATOLOGY,
  ENDOCRINOLOGY,
  FAMILY_MEDICINE,
  GERIATRICS,
  NEUROLOGY,
  NEUROSURGERY,
  GYNECOLOGY,
  ONCOLOGY,
  PEDIATRICS,
  PSYCHIATRY,
  PULMONOLOGY,
  RADIOLOGY,
  UROLOGY
}

